[package]
name = "mcp"
version = "0.2.0"
edition = "2021"
license = "No License"
repository = "https://github.com/WKGHMiner/RhythmGame/"


[lib]
path = "./src/lib.rs"
crate-type = ["cdylib", "rlib"]


[dependencies]
regex = "1.11.1"
once_cell = "1.20.2"
wasm-bindgen = "0.2.99"
hound = "3.4"