[package]
name = "mcp"
version = "0.1.0"
author = ["Miner"]
edition = "2021"

[lib]
path = "./src/lib.rs"
crate-type = ["cdylib", "rlib"]


[dependencies]
regex = "1.11.1"
once_cell = "1.20.2"
wasm-bindgen = "0.2.97"